version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-docker
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # Jenkins data
      - jenkins_home:/var/jenkins_home
      # Docker socket for Docker-in-Docker
      - /var/run/docker.sock:/var/run/docker.sock
      # Docker binary (adjust path based on your system)
      - /usr/local/bin/docker:/usr/bin/docker
    environment:
      # Skip initial setup wizard (optional)
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      # Docker host
      - DOCKER_HOST=unix:///var/run/docker.sock
    user: root  # Required for Docker socket access
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  jenkins_home:
    driver: local

networks:
  default:
    name: jenkins-network