# Override for development - docker-compose up will use this automatically
services:
  server:
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app/server
    command: npm run dev:server

  client:
    build:
      args:
        - VITE_SERVER_URL=http://localhost:3001
    volumes:
      - ./client/src:/app/src
    command: npm run dev